# Satori 协议配置

# HTTP API 终结点
http_endpoint: http://127.0.0.1:5140/satori/v1

# WebSocket 事件终结点
ws_endpoint: ws://127.0.0.1:5140/satori/v1/events

# API 访问令牌
token: ""

# 平台名称
platform: satori

# 超时时间 (毫秒)
timeout: 60000

# 心跳间隔 (毫秒)
heartbeat_interval: 10000